version: '3.4'

services:
  builddocs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/drand
    command: make -C docs html
  viewdocs:
    image: nginx
    ports:
      - '57781:80'
    volumes:
      - ./docs/_build/html:/usr/share/nginx/html
