version: '3'

services:
  drand-client-1:
    image: sbellem/drand:a40dc25e
    container_name: drand1
    entrypoint: /data/client-script.sh
    volumes:
      - ./data:/data:z
    networks:
      - drandnetwork
    environment:
      PORT: 8080
      LEADER: 1
  drand-client-2:
    image: sbellem/drand:a40dc25e
    container_name: drand2
    entrypoint: /data/client-script.sh
    volumes:
      - ./data:/data:z
    networks:
      - drandnetwork
    environment:
      PORT: 8081
  drand-client-3:
    image: sbellem/drand:a40dc25e
    container_name: drand3
    entrypoint: /data/client-script.sh
    volumes:
      - ./data:/data:z
    networks:
      - drandnetwork
    environment:
      PORT: 8082
  drand-client-4:
    image: sbellem/drand:a40dc25e
    container_name: drand4
    entrypoint: /data/client-script.sh
    volumes:
      - ./data:/data:z
    networks:
      - drandnetwork
    environment:
      PORT: 8083
  drand-client-5:
    image: sbellem/drand:a40dc25e
    container_name: drand5
    entrypoint: /data/client-script.sh
    volumes:
      - ./data:/data:z
    networks:
      - drandnetwork
    environment:
      PORT: 8084

networks:
  drandnetwork:
    ipam:
      driver: default
      config:
          - subnet: 172.15.238.0/24
